(() => {
  const results = [];
  const assert = (condition, description) => {
    if (!condition) throw new Error(description);
    results.push(description);
  };
  const md = '# Plan / 项目计划\nIntro\n\n## Research\nFirst chapter\n\n### Evidence\nNeedle inside a folded child.\n\n###### Detail\nDeep detail\n\n## Delivery\nSecond chapter\n\n### Evidence\nOther evidence\n\n## Links and `code`\n[Example](https://example.com)\n\n```md\n# Not a heading\n```';
  const heading = (title) => Array.from(document.querySelectorAll('.loom-section')).find(s => s.dataset.title === title);
  const click = (title, altKey = false) => heading(title).firstElementChild.querySelector('button').dispatchEvent(new MouseEvent('click', { bubbles: true, altKey }));
  const isClosed = title => heading(title).lastElementChild.hidden;
  window.__loomRender(md, true, 'test/plan', []);
  assert(sections.length === 7, 'Six heading levels work; fenced code is not a section');
  assert(heading('Research').contains(heading('Detail')), 'Skipped heading levels retain nesting');
  assert(new Set(sections.map(s => s.dataset.foldKey)).size === 7, 'Repeated heading names have distinct paths');
  click('Evidence');
  click('Research');
  assert(isClosed('Research') && !isClosed('Delivery'), 'Folding stops at the next sibling heading');
  click('Research');
  assert(isClosed('Evidence'), 'Expanding a parent preserves its child fold');
  click('Research', true);
  assert(isClosed('Research') && isClosed('Detail'), 'Option-click includes descendant sections');
  window.__loomRender(md.replace('First chapter', 'Updated first chapter'), false, 'test/plan', []);
  assert(isClosed('Research') && isClosed('Detail'), 'Refreshing the same document retains folds');
  window.__loomFindQuery('Needle');
  assert(findHits.length === 1 && !isClosed('Research') && !isClosed('Evidence'), 'Find reveals a match inside folded ancestors');
  click('Delivery');
  window.__loomFindHide();
  assert(isClosed('Delivery') && !document.querySelector('mark.loom-hit'), 'Closing find retains manual folds and removes marks');
  assert(document.querySelector('#content a').getAttribute('href') === 'https://example.com', 'Links remain intact through folding and find');
  document.getElementById('fold-all').click();
  assert(!isClosed('Plan / 项目计划') && isClosed('Research') && isClosed('Delivery'), 'Collapse all leaves chapter headings discoverable');
  document.getElementById('unfold-all').click();
  assert(sections.every(s => !s.lastElementChild.hidden), 'Expand all restores every section');
  const saved = [heading('Delivery').dataset.foldKey];
  window.__loomRender(md, true, 'test/other', []);
  assert(!isClosed('Delivery'), 'A different document has independent fold state');
  window.__loomRender(md, true, 'test/plan', saved);
  assert(isClosed('Delivery'), 'Reopening a document restores saved fold state');
  window.__loomRender('', false, 'test/plan', []);
  assert(document.getElementById('reading-tools').hidden && findHits.length === 0, 'Empty documents clear search and section controls');
  const large = '# Long plan\n' + Array.from({ length: 160 }, (_, i) => `\n## Chapter ${i}\n${'Readable content with 中文 and a little detail. '.repeat(30)}\n### Notes ${i}\n- Item\n- Item\n`).join('');
  const start = performance.now();
  window.__loomRender(large, true, 'test/large', []);
  const renderMs = performance.now() - start;
  const foldStart = performance.now();
  document.getElementById('fold-all').click();
  const foldMs = performance.now() - foldStart;
  assert(sections.length === 321 && !sections[0].lastElementChild.hidden, 'Large plans fold without losing their outline');
  window.__loomRender(md, true, 'test/preview', []);
  document.getElementById('fold-all').click();
  click('Research');
  return { passed: results.length, results, largePlan: { characters: large.length, headings: 321, renderMs, foldMs } };
})();
